services:
  nginx:
    image: nginx:latest
    ports:
      - "4001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    depends_on:
      - php
    networks:
      - frontend
      - backend

  php:
    image: php:7.4-fpm
    volumes:
      - ./html:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: c
      MYSQL_PASSWORD: p
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "6001:80"
    depends_on:
      - mysql
    networks:
      - backend

networks:
  frontend:
  backend:
